### PR TITLE
Fix some documentation issues found in Scrutinizer

### PR DESCRIPTION
**Pull request by michaelbutler**
Fixed some of the issues found in Scrutinizer:

* PHPDoc for read-only properties
* Defined protected properties for some dynamically defined properties.

### CODE REVIEW

**Comment by julianseeger** [comment]
Thanks for the PR but as long as nobody fixes the build (=the tests for the current phpunit version), nothing will get merged :(

**Comment by michaelbutler** [comment]
Totally agree, I'm going to attempt to figure out why it's failing and fix
it in a separate pr.  For starters, it passes on my laptop with the same
versions of everything.

**Comment by julianseeger** [comment]
Now that build is green (or will be after a rebase/merge), most of this PR looks pretty redundant to me (especially the `@package` annotation and the `Class` DocBlock, I mean seriously ^^) but if it satisfies some IDEs and probably won't hurt anyone.

Just out of interest: which IDEs have problems with autocompletion of real methods when a magic method is present?

**Comment by michaelbutler** [comment]
@julianseeger you're right about 'Class' and '@package', those really aren't needed so I'll take them out. Basically what I was going by was the Scrutinizer job. I think all that stuff can be customized maybe to turn certain features off. Still, for things like @property-read I think it does actually make sense. I'm using PHPStorm for the record. 
I also added `protected $variable` statements which I think is definitely the most important thing to add. It's bad practice in PHP to define variables on the fly like $this->foo inside a constructor or anywhere, without having an explicit private/protected/public definition in the class.

**Comment by michaelbutler** [comment]
ok, no idea why the build is failing for mostly just comment PHPdoc changes. will look into it later.

**Comment by michaelbutler** [comment]
Closing until further notice.

**Pull request closed without merging**
