### PR TITLE
uniqid() is not unique enough so add usleep to ensure uniqueness

### PR DESCRIPTION
**Pull request by chbiel**
When uniqid is executed to fast in a row the generated id's are unique. usleep ensures a uniqueid

would be 0.12.1 i think

### CODE REVIEW

**Comment by chbiel** [comment]
okay :D there is something new with scrutinizer...

**Comment by julianseeger** [comment]
**Scruzinizer:**
Ignore scrutinizer. You could remove the
```YAML
build_failure_conditions:
  - 'issues.new.exists
```
from the .scrutinizer.yml to make the build pass after a merge. We can turn it back on after those issues are addressed.

**uniqid:**
Ok, obvious bug. If the loop is faster than a ms, we get doubled results. But don't you get goosebumps when writing a usleep? ^^
`uniqid($i)` and `uniqid('', true)` should both fix the issue without a sleep because the token ($i) is unique within the process and the true should generate enough entropy to be unique within the same ms, shouldn't they?. (preferable prefix with $i because the $more_entropy flag generates uniqids with dots).

**Comment by chbiel** [comment]
I tried ```uniqid('', true)``` but the generated number contains "." what I didnt find that beautiful. ´´´uniqid($i)´´´ did'nt came to my mind but is used now ;)

**Comment by julianseeger** [comment]
>would be 0.12.1 i think

thanks :+1:

**Pull request merged**
