### PR TITLE
Incorrent xml output if I use the dataProvider in tests

### PR DESCRIPTION
**Pull request by drefixs**
Incorrent xml output if I use the dataProvider in tests #19

### CODE REVIEW

**Comment by julianseeger** [comment]
Thanks for the patch.
Could you please add a small test for this?

**Comment by drefixs** [comment]
Ok if i have time then, i will add some fixture junit xml for dataProvider and make small test for that.

**Comment by drefixs** [comment]
Pls review I did small test for this.
thx.
@julianseeger

**Comment by julianseeger** [comment]
Thx. As the fix is referencing #19 which is pretty old, I would merge this PR.

But if you have some time left @drefixs there are some issues that could be fixed before the branch is merged:
1. even though the log makes much more sense than before (no empty names etc.), it still differs a lot from the phpunit log (compared to phpunit 5.0.9). I don't know how close we need to get, but at least a level of "testsuite" is missing
2. the tests executes every new line but it doesn't logically cover it
The lines [94](https://github.com/brianium/paratest/pull/185/files#diff-f9112ee9dade2252a9d4620293b76d50R94) and [95](https://github.com/brianium/paratest/pull/185/files#diff-f9112ee9dade2252a9d4620293b76d50R95) contain a lot of logic but the tests only checks for not-emptyness. Accordingly this would make the tests pass:
```PHP
$class = ".";
$file = ".";
```
So there is a test missing that checks if the values of $class and $file make sense.
And line 102 ```if (empty($case->file)) {``` can be removed without failing the test.

Feel free to fix these issues. ;)  It could be merged without further work, but #19 would be left open.

**Comment by drefixs** [comment]
Thx, for review @julianseeger

1. Obtain https://raw.githubusercontent.com/windyroad/JUnit-Schema/master/JUnit.xsd PHPUnit performs invalid logs. testsuite haven't contain itself. It's Any matter to do log closer to PHPUnit format because it is invalid. The main target of this fix is to fix a critical  format requirement to make this log readable for report systems. There isn't enough data to do this absolutely valid to JUnit.xsd.

2. Thanks, these are right remarks, and I will carry out more complex unit tests

Thanks.

**Comment by drefixs** [comment]
I decided to do logic more simple because it's bad idea to try get something from nested testsuite it doesn't aggregate any data from junit.xml log. I think to fix this problem directly there is 2-way. Wait for PHPUnit fix they JUnit log According to JUnit.xsd or rewrite paratest  Reader and Writer According to JUnit.xsd and add some adapter to Reader for invalid PHPUnit JUnit logs.

2. Done pls review :).

**Comment by julianseeger** [comment]
Looks good. I'll check this tomorrow.

**Comment by julianseeger** [comment]
Alright, thx for your additional fixes. (2) is fine now and with point (1) you are probably right. There is no hint anywhere that nested testcases are a valid occurence, not even in the phpunit docs as some kind of special case so I would also consider that a bug in phpunit. No point in adding buggy behavior just for compliance.

**Pull request merged**
